### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by gurumukhi** [VI5H4L/Searchinator#1]
This look like an interesting addon. Thanks for working on it.

Is this working on well Firefox?

**Comment by VI5H4L** [comment]
Thank You so much for the guidance and appreciation sir. Yes its working well in Firefox too..

Below is the reference image
![image](https://user-images.githubusercontent.com/107054166/227775429-f8d8d6e7-3ffb-4480-8cdd-02cdd52193ac.png)
